name: algorand_dart
description: Unofficial community SDK to interact with the Algorand network, for Dart & Flutter
version: 2.0.0-dev.14
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/algorand-dart
issue_tracker: https://github.com/RootSoft/algorand-dart/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  # Ed25519
  cryptography: ^2.5.0

  # SHA512/256
  crypto: ^3.0.2

  # Base32
  base32: ^2.1.3

  # Convert
  convert: ^3.1.1

  # Easily work with bytes
  buffer: ^1.2.0

  # Equatable
  equatable: ^2.0.5

  # JSON Annotation
  json_annotation: ^4.8.0

  # Equality
  collection: ^1.17.0

  # HTTP & REST
  dio: ^5.8.0+1
  retrofit: ^4.4.2

  # Messagepack
  algorand_msgpack: ^1.0.1

  algorand_json: ^0.0.2

dev_dependencies:
  # Testing framework
  test: ^1.25.15

  # Build Runner & Source Generation
  build_runner: ^2.4.15

  # Linter
  lints: ^2.1.0

  # JSON Serialization
  json_serializable: ^6.8.0

  # Retrofit
  retrofit_generator: ^9.1.9

dependency_overrides:
  dio: ^5.8.0+1